upstream api { 
    server exchange-api-1:3000;
}

upstream log_api {
    server exchange-log-api-1:3001;
}

server {
    listen 80;

    location = /log {
        proxy_pass http://log_api;
    }

    location / {
        proxy_pass http://api/;
    }
}