{
 "title": "Main dashboard Copy2",
 "time": { "from": "2026-09-25T04:50:51.000Z", "to": "2026-09-25T04:54:57.000Z" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "server", "query": "artillery-api" },
   {
    "name": "container",
    "query": "exchange-api-1, exchange-api-2, exchange-api-3, exchange-cadvisor-1, exchange-grafana-1, exchange-graphite-1,  exchange-nginx-1, exchange_bbox_1"
   },
   { "name": "memory4GB", "query": "4294967296" }
  ]
 },
 "panels": [
  {
   "title": "Response Time (client-side)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias(stats.gauges.$server.scenarioDuration.p99, 'P99')"
    },
    {
     "target": "alias(stats.gauges.$server.scenarioDuration.p95, 'P95')"
    },
    {
     "target": "alias(stats.gauges.$server.scenarioDuration.p50, 'P50')"
    }
   ]
  },
  {
   "title": "Scenarios Launched",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.$server.scenarioCounts.*)"
    }
   ]
  },
  {
   "title": "Response Time by Endpoint (server-side)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode(exclude(stats.timers.exchange.latency.*.upper_95, 'accounts_balance'), 4)"
    }
   ]
  },
  {
   "title": "Requests State",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(diffSeries(integral(stats.gauges.$server.scenariosCreated), integral(sumSeries(stats.gauges.$server.scenariosCompleted, stats.gauges.$server.scenariosAvoided, stats.gauges.$server.errors.*))), 'Pending')"
    },
    {
     "target": "alias(sumSeries(grep(stats.gauges.$server.codes.*, '\\.[1-3][0-9]{2}$')), 'Completed')"
    },
    {
     "target": "alias(sumSeries(grep(stats.gauges.$server.codes.*, '\\.4[0-9]{2}$')), 'Limited')"
    },
    {
     "target": "alias(sumSeries(grep(stats.gauges.$server.codes.*, '\\.5[0-9]{2}$'), sumSeries(stats.gauges.$server.errors.*)), 'Failed')"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "alias(asPercent(derivative(summarize(stats.gauges.cadvisor.$container.cpu_cumulative_usage, '10s', 'max')), 10000000000), 'CPU')"
    },
    {
     "target": "alias(asPercent(stats.gauges.cadvisor.$container.memory_working_set, $memory4GB), 'Memory')"
    }
   ]
  },
  {
   "title": "Currency (USD)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "target": "aliasByMetric(stats_counts.exchange.volume.*)"
    }
   ]
  },
  {
   "title": "Net Currency (USD)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "target": "aliasByMetric(stats_counts.exchange.net.*)"
    }
   ]
  }
 ]
}